{
	"version": 1481822542,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background.png",
		"images/ground-sheet0.png",
		"images/platform1-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/wall1-sheet0.png",
		"images/bomb-sheet0.png",
		"images/bomb-sheet1.png",
		"images/safety-sheet0.png",
		"images/background2-sheet0.png",
		"images/background3-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/board-sheet0.png",
		"images/submitbutton-sheet0.png",
		"images/menubutton-sheet0.png",
		"images/arrows-sheet0.png",
		"images/textfield-sheet0.png",
		"media/jump_03.m4a",
		"media/jump_03.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/jump_01.m4a",
		"media/jump_01.ogg",
		"media/atari_boom.m4a",
		"media/atari_boom.ogg",
		"media/boom2.m4a",
		"media/boom2.ogg",
		"media/wrong-answer-sound-effect.m4a",
		"media/wrong-answer-sound-effect.ogg",
		"media/jumping bat nes.m4a",
		"media/jumping bat nes.ogg",
		"media/menu_music.m4a",
		"media/menu_music.ogg",
		"loading-logo.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png"
	]
}